"""add columns

Revision ID: 2c5e28ff2453
Revises: 3a4aec7bde76
Create Date: 2023-09-07 23:59:53.194164+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c5e28ff2453'
down_revision = '3a4aec7bde76'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_experiences_user_id_fkey', 'user_experiences', type_='foreignkey')
    op.create_foreign_key(None, 'user_experiences', 'user_detail', ['user_id'], ['user_id'])
    op.drop_constraint('user_expertises_user_id_fkey', 'user_expertises', type_='foreignkey')
    op.create_foreign_key(None, 'user_expertises', 'user_detail', ['user_id'], ['user_id'])
    op.drop_constraint('user_interests_user_id_fkey', 'user_interests', type_='foreignkey')
    op.create_foreign_key(None, 'user_interests', 'user_detail', ['user_id'], ['user_id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_interests', type_='foreignkey')
    op.create_foreign_key('user_interests_user_id_fkey', 'user_interests', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_expertises', type_='foreignkey')
    op.create_foreign_key('user_expertises_user_id_fkey', 'user_expertises', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'user_experiences', type_='foreignkey')
    op.create_foreign_key('user_experiences_user_id_fkey', 'user_experiences', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
