"""add columns

Revision ID: 1be41efbf7f7
Revises: 6204d741204f
Create Date: 2023-09-07 23:14:13.993792+09:00

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1be41efbf7f7'
down_revision = '6204d741204f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
