"""add columns

Revision ID: 6204d741204f
Revises: 9f17abad6273
Create Date: 2023-09-07 23:06:48.151554+09:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6204d741204f'
down_revision = '9f17abad6273'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_leave')
    op.drop_table('user_active')
    op.add_column('user_detail', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_detail', 'updated_at')
    op.create_table('user_active',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_active_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='user_active_pkey')
    )
    op.create_table('user_leave',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='user_leave_user_id_fkey'),
    sa.PrimaryKeyConstraint('user_id', name='user_leave_pkey')
    )
    # ### end Alembic commands ###
